- name: Adicionar chaves SSH
  hosts: all
  become: yes
  tasks:
    # - name: Criar diretório .ssh (caso não exista)
    #   ansible.builtin.file:
    #     path: /home/deploy/.ssh
    #     state: directory
    #     owner: deploy
    #     group: deploy
    #     mode: '0700'

    # - name: Copiar authorized_keys deploy
    #   ansible.builtin.copy:
    #     src: ../../0.Global/authorized_keys/deploy/authorized_keys
    #     src: deploy/authorized_keys
    #     dest: /home/deploy/.ssh/
    #     owner: deploy
    #     group: augen
    #     mode: '0600'
        
    - name: Copiar authorized_keys dos
      ansible.builtin.copy:
        # src: ../../0.Global/authorized_keys/dos/authorized_keys
        src: dos/authorized_keys
        dest: /home/dos/.ssh/
        owner: dos
        group: augen
        mode: '0600'

# run with:
  # sudo -E ansible-playbook -i ../../1.RKS/inventory-RKS.ini install_node_exporter.yml 
  # sudo -E ansible-playbook -i ../../1.CMR/inventory-CMR.ini install_node_exporter.yml