---
- name: K8s setup
  hosts: all
  become: true  # Use sudo

  tasks:
    - name: Install dependencies
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present
      
    - name: Disable swap
        command: swapoff -a
        when: ansible_swaptotal_mb > 0