[default]
theBasic-01 ansible_host=${IP01} ansible_port=22
theBasic-02 ansible_host=${IP02} ansible_port=22

[all:vars]
ansible_user=ubuntu
; ansible_become_password=x
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
dev_ssh_key="x"  
dos_password=${dos_password}