---
- name: Infra setup
  hosts: all
  become: true  # Use sudo

  tasks:

    - name: Ensure group 'miguel' exists #create miguel group
      group:
        name: miguel
        state: present

    - name: Create user 'deploy'
      user:
        name: deploy
        shell: /bin/bash
        groups: miguel,docker
        append: yes
        create_home: yes
        password: "*"  # Disables password login

    - name: Create .ssh directory for deploy
      file:
        path: /home/deploy/.ssh
        state: directory
        owner: deploy
        group: deploy
        mode: '0700'

    - name: Set authorized_keys for deploy
      copy:
        content: "{{ dev_ssh_key }}"
        dest: /home/deploy/.ssh/authorized_keys
        owner: deploy
        group: deploy
        mode: '0600'

    - name: Create user 'dos'
      user:
        name: dos
        shell: /bin/bash
        groups: miguel,sudo,docker
        append: yes
        create_home: yes
        password: "{{ dos_password }}"
    
    - name: Create .ssh directory for dos
      file:
        path: /home/dos/.ssh
        state: directory
        owner: dos
        group: dos
        mode: '0700'

    - name: Set authorized_keys for dos
      copy:
        content: "{{ dev_ssh_key }}"
        dest: /home/dos/.ssh/authorized_keys
        owner: dos
        group: dos
        mode: '0600'

    - name: Ensure sshd_config.d directory exists
      file:
        path: /etc/ssh/sshd_config.d
        state: directory
        mode: '0755'

    - name: Deploy custom SSHD configuration
      copy:
        dest: /etc/ssh/sshd_config.d/custom.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          Port 22
          PasswordAuthentication no
          PermitRootLogin no
          PermitEmptyPasswords no
          AllowGroups miguel

          Match Group miguel
              PermitTunnel yes
              AllowAgentForwarding no
              AllowTcpForwarding yes
              PubkeyAuthentication yes

    - name: Validate sshd configuration syntax
      command: sshd -t
      register: sshd_check
      failed_when: sshd_check.rc != 0
      changed_when: false

    - name: Restart SSH service
      systemd:
        name: ssh
        state: restarted
        enabled: true
