---
- name: Infra setup
  hosts: all
  become: true  # Use sudo

  tasks:
    - name: Set the hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Ensure /etc/hosts has correct hostname mapping
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1\s+'
        line: "127.0.1.1 {{ inventory_hostname }}"
        state: present